version: "3.3"

services:
  backend:
    container_name: challenge-backend
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      APP_ENV: ${APP_ENV:-DOCKER}
      BASE_URL: ${BASE_URL:-0.0.0.0}
      API_PORT: ${API_PORT:-8080}

  database:
    image: postgres:alpine
    container_name: challenge-database
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
