version: "3.9"

services:
  backend:
    container_name: challenge-backend
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      APP_ENV: ${APP_ENV:-DOCKER}
      BASE_URL: ${BASE_URL:-0.0.0.0}
      API_PORT: ${API_PORT:-8080}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@gmail.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin1234}
      JWT_SERCET: ${JWT_SECRET:-jwtsecret1234}
      PG_HOST: ${PG_HOST:-database}
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER:-postgres}
      PG_PASSWORD: ${PG_PASSWORD:-postgres}
      PG_DBNAME: ${PG_DBNAME:-challenge}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      GMAP_API_KEY: ${GMAP_API_KEY}
      PROJECT_ID: ${PROJECT_ID}
      BUCKET: ${BUCKET}

  database:
    image: postgres:alpine
    container_name: challenge-database
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    volumes:
      - postgres-data2:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  postgres-data2:
