// Code generated by MockGen. DO NOT EDIT.
// Source: internal/informations/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/informations/repository.go -destination=internal/informations/mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/esgi-challenge/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(informations *models.Informations) (*models.Informations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", informations)
	ret0, _ := ret[0].(*models.Informations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(informations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), informations)
}

// Delete mocks base method.
func (m *MockRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockRepository) GetAll() (*[]models.Informations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]models.Informations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockRepository) GetById(id uint) (*models.Informations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*models.Informations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockRepository)(nil).GetById), id)
}

// GetBySchoolId mocks base method.
func (m *MockRepository) GetBySchoolId(schoolId uint) (*[]models.Informations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchoolId", schoolId)
	ret0, _ := ret[0].(*[]models.Informations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySchoolId indicates an expected call of GetBySchoolId.
func (mr *MockRepositoryMockRecorder) GetBySchoolId(schoolId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchoolId", reflect.TypeOf((*MockRepository)(nil).GetBySchoolId), schoolId)
}

// GetBySchoolIdAndId mocks base method.
func (m *MockRepository) GetBySchoolIdAndId(schoolId, informationId uint) (*models.Informations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchoolIdAndId", schoolId, informationId)
	ret0, _ := ret[0].(*models.Informations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySchoolIdAndId indicates an expected call of GetBySchoolIdAndId.
func (mr *MockRepositoryMockRecorder) GetBySchoolIdAndId(schoolId, informationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchoolIdAndId", reflect.TypeOf((*MockRepository)(nil).GetBySchoolIdAndId), schoolId, informationId)
}
