// Code generated by MockGen. DO NOT EDIT.
// Source: internal/campus/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/campus/usecase.go -destination=internal/campus/mock/usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/esgi-challenge/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUseCase) Create(user *models.User, campus *models.Campus) (*models.Campus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user, campus)
	ret0, _ := ret[0].(*models.Campus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUseCaseMockRecorder) Create(user, campus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), user, campus)
}

// Delete mocks base method.
func (m *MockUseCase) Delete(user *models.User, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", user, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUseCaseMockRecorder) Delete(user, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUseCase)(nil).Delete), user, id)
}

// GetAll mocks base method.
func (m *MockUseCase) GetAll() (*[]models.Campus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]models.Campus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUseCaseMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUseCase)(nil).GetAll))
}

// GetAllBySchoolId mocks base method.
func (m *MockUseCase) GetAllBySchoolId(schoolId uint) (*[]models.Campus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBySchoolId", schoolId)
	ret0, _ := ret[0].(*[]models.Campus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBySchoolId indicates an expected call of GetAllBySchoolId.
func (mr *MockUseCaseMockRecorder) GetAllBySchoolId(schoolId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBySchoolId", reflect.TypeOf((*MockUseCase)(nil).GetAllBySchoolId), schoolId)
}

// GetById mocks base method.
func (m *MockUseCase) GetById(id uint) (*models.Campus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*models.Campus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUseCaseMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUseCase)(nil).GetById), id)
}

// Update mocks base method.
func (m *MockUseCase) Update(user *models.User, id uint, updatedCampus *models.Campus) (*models.Campus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user, id, updatedCampus)
	ret0, _ := ret[0].(*models.Campus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUseCaseMockRecorder) Update(user, id, updatedCampus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), user, id, updatedCampus)
}
