name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.22.2"

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Checkout the repo
        uses: actions/checkout@v4

      # - name: Test
      #   run: go test ./...

  building:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build
        run: go build cmd/api/main.go
