name: Deployment

on:
  push:
    branches:
      - main
jobs:
  build-push-image:
    name: Deploy image to gcloud artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GCP with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - name: Configure docker to use gcp 
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            europe-west1-docker.pkg.dev/challenge-esgi-419811/challenge-esgi-service-repository/backend-preprod:${{ github.sha }}
            europe-west1-docker.pkg.dev/challenge-esgi-419811/challenge-esgi-service-repository/backend-preprod:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  deploy-cloud-run:
    name: Deploy To Cloud run
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - name: Check out the repo
        uses: "actions/checkout@v4"

      - name: Log in to GCP with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "challenge-esgi-preprod-backend"
          image: "europe-west1-docker.pkg.dev/challenge-esgi-419811/challenge-esgi-service-repository/backend-preprod:latest"
          region: europe-west1
          env_vars: |
            API_PORT=8080
            APP_ENV=PROD
            BASE_URL=0.0.0.0
            JWT_TOKEN=${{ secrets.JWT_TOKEN }}
            PG_DBNAME=${{ secrets.PG_DBNAME }}
            PG_HOST=${{ secrets.PG_HOST }}
            PG_PASSWORD=${{ secrets.PG_PASSWORD }}
            PG_PORT=${{ secrets.PG_PORT }}
            PG_USER=${{ secrets.PG_USER }}
            SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            SMTP_HOST=${{ secrets.SMTP_HOST }}
            GIN_MODE=release
